# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-10 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='exclude',
        ),
        migrations.AddField(
            model_name='item',
            name='excludes',
            field=models.TextField(blank=True, help_text='Separate each item by comma', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='contents',
            field=models.TextField(help_text='Separate each item by comma'),
        ),
    ]
